title: Technocidal
email: hello@technocidal.com
description: "Technocidal is created by me, Johannes Ebeling. I'm a father, software engineer and aspiring coffee snob."
url: https://technocidal.com
author:
  name: Johannes Ebeling
  email: hello@technocidal.com

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

google_analytics: G-BNNY2F0WSN

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-spaceship